### ISSUE TITLE
converting energy to a "normal form" appears to affect results

### ISSUE THREAD

**Issue by kmonson** [Electrostatics/graphcut#1]
The normalization step of the graph cut is supposed to be benign as to the results. It is meant to be an optimization step. We need to figure out if the normalization process actually affects the results or if I'm just doing it wrong.

**Comment by kmonson** [comment]
It turns out that converting to a normal for is REQUIRED for the graph cut to work properly. It eliminates edges in the graph with a negative capacity. The java graph cut lib will fail without normalization, the python lib we use is treating negative capacities as 0 (which is WRONG) and this accounts for the difference.

**Comment by keith923** [comment]
Is there an issue to address the problem in the Python code?

In a case like this, where an issue references a bug, or other further work, I like to create the new issue, and then reference it in a comment so that there is a linkage to the new issue.  Could you do that @kmonson?

**Comment by kmonson** [comment]
Yeah, there is "figure out why they are different" issue here #2.

**Comment by keith923** [comment]
Thanks @kmonson!

Actually, I do have a comment.  It seems like "figuring out why they are different" is distinct from "Python treating negative capacities as 0 (which is WRONG)".  While the latter may be part of the explanation of the former, it seems like a separate issue.

In fact, it seems like issue #2 may ultimately serve to be an issue generator, with lots of different problems that are related, but still distinct.  Does that make sense?
