### ISSUE TITLE
Differences in results between java and python versions of graphcut code.

### ISSUE THREAD

**Issue by kmonson** [Electrostatics/graphcut#2]

**Comment by kmonson** [comment]
![1jhg](https://cloud.githubusercontent.com/assets/2049915/9690896/f3b106fe-52f3-11e5-9b91-800bdc5b9879.png)
![1jkc](https://cloud.githubusercontent.com/assets/2049915/9690894/f3b011c2-52f3-11e5-8424-5cab50c57070.png)
![1plc](https://cloud.githubusercontent.com/assets/2049915/9690895/f3b0790a-52f3-11e5-8746-a90a126f2172.png)
![1f94](https://cloud.githubusercontent.com/assets/2049915/9690893/f3addf38-52f3-11e5-8989-854396b3a7f0.png)

**Comment by sobolevnrm** [comment]
Some of those differences are non-trivial.  Are these the plots that I
generated or something new?

**Comment by kmonson** [comment]
Some of them are the same. The "no normal" stuff is the same input with the
"Make normal form" code skipped.

**Comment by kmonson** [comment]
Emilie and I went over this with a fine toothed comb on Friday. Here is what we found or what I knew from before in no particular order. This is sort of a stream of consciousness and I'll add to it as I think of stuff.

Emilie's code always seems to find a slightly better result with each cut IF they are different.

In some cuts my graph cut will be certain about a residue state and be wrong. Usually this happens to a single residue. While we are not completely sure, this could account for all of the difference between the two code bases. This seems to be the core issue. In 1F94 the total minimum energies start to diverge around pH 3.9 but do not get very far apart. 

If we correct the wrong residue states and use the resulting overall state (matching the overal state in Emilie's code) of the residue to get the total energy of the protein it matches the results of Emilie's code. This seems to indicate that the normal form has the correct values. 

Manually creating a flow graph created by Emilie's code in networkx (and using the same max flow algorithm) results in the exact same cut. We can conclude that Networkx is not the problem.

Using different minimum cut algorithms (networkx has several) results in different cuts. This is perfectly normal as there are many possible cuts that will give the same minimum cut value. As long as it does not lead to an incorrect assertion about the state of a residue it's fine. 

In some cases because of a bug in Emilie's code an entire step will be brute forced. Does not seem to affect results, just make things slow (of course).

Things I need to double check or verify:

The resulting normalized form in the two programs are different. This is because the normalization process is order dependent. Changing the order in my code to match Emilie's should result in the same normal form.

The initial state of the interaction energies and residue energies (after simplification and before normalization) matches Emilie's code exactly.

**Comment by kmonson** [comment]
The plan:
1. Verify every energy value (interaction and residue) pre-normalization at a non-zero pH value. (Should not be too hard)
2. Verify every energy value (interaction and residue) post-normalization at a non-zero pH value. This will be hard as normalization is order dependent. I will need to make it process residues in the same order as Emilie's code.
3. Once 2 is done, verify that the resulting graphs created by each program are the same.

**Comment by kmonson** [comment]
```
4. If none of that works, cry.
```

**Comment by kmonson** [comment]
Changed every internal dictionary in the protein complex class to an Ordered Dict to see if it affects the results. 

It does. This means that there is order dependent behavior somewhere in the code.

**Comment by lizutah** [comment]
@kmonson - Does it change the results in a good way?

**Comment by kmonson** [comment]
No, it's just different. It's also bad because the order of residues are processed should not affect the results at all.

**Comment by kmonson** [comment]
643d4fa44cb9d49e19fd001deb968083df74b3da
