### ISSUE TITLE
All HIS curves are identical on all proteins tested.

### ISSUE THREAD

**Issue by kmonson** [Electrostatics/graphcut#3]
Seriously. Every single one. Exactly the same. Is this normal? 

Check out the HIS graphs in #2.

**Comment by sobolevnrm** [comment]
Nope, that's not right.  What results does PDB2PKA give?  What does Emilie
say?

**Comment by eahogan** [comment]
Looking at figure 10 in the paper, the HIS pka values from PDB2PKA are also pretty concentrated. Not exactly the same, but much more concentrated than the values for other residues. Perhaps this is ok? The other option is something with the RT or kT normalization factor again.
